# Generated by Django 4.2.30 on 2026-09-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(help_text='Ej: Familia Maldonado Garza', max_length=150)),
                ('mensaje_anecdota', models.TextField(blank=True, null=True)),
                ('asistira', models.BooleanField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SugerenciaCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_o_enlace', models.CharField(max_length=255)),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('confirmado', models.BooleanField(default=False)),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='invitaciones.invitacion')),
            ],
        ),
    ]
