# Generated by Django 4.2.30 on 2026-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='codigo',
            field=models.CharField(default=1, help_text='Ej: FAM-01', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
